---
- src: https://github.com/mtbvang/ansible-kubernetes-helm
  name: helm
  version: v1.2.5
- src: https://github.com/mtbvang/ansible-kubectl
  name: kubectl
  version: v1.1.11
- src: https://github.com/mtbvang/ansible-role-terraform
  name: terraform
  version: 'v0.1.0'
- src: https://github.com/geerlingguy/ansible-role-java
  name: java
  version: '1.7.6'
  